#!/usr/bin/env python
from GroupGenerator import GroupGenerator
from TestGenerator import TestGenerator
from StepGenerator import StepGenerator
from DrawGenerator import DrawGenerator
from DropGenerator import DropGenerator

#the point of this is to make a method based on the TLL file from Feb 6th that can produce a TLL file that allows you to
#fill some amount of wells on a 96 well rack with a given solution
#dilute the solution by transferring an aliquot of it to a different 96 well rack and then adding DH2O from another
#resevoir.

